apiVersion: v1
kind: Service
metadata:
  name: alpine-ampache
  labels:
    run: alpine-ampache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: alpine-ampache
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-ampache
  labels:
    app: alpine-ampache
spec:
  selector:
    matchLabels:
      app: alpine-ampache
      tier: backend
  template:
    metadata:
      labels:
        app: alpine-ampache
        tier: backend
    spec:
      containers:
      - name: php-alpine
        image: oneko/ampache-alpine-nginx
        ports:
        - containerPort: 80
          name: http
        resources:
         requests:
          memory: "128Mi"
          cpu: "100m"
         limits:
          memory: "192Mi"
          cpu: "200m"

