apiVersion: v1
kind: PersistentVolume
metadata:
 name: code-v
 labels:
  name: code-v
 spec:
  capacity: 
   storage: 128Mi
  storageClassName: standard
  accessMode:
  - ReadWriteOnce
  gcePersistentDisk:
   pdName: code-v
   fsType: ext4
   readOnly: false

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: hostvol
spec:
 resources:
  requests:
   storage: 128Mi
 selector:
  matchLabels:
   name: code-v
 accessModes:
 - ReadWriteOnce
