apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: alpine-ampache
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: alpine-ampache
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine-ampache
        tier: frontend
        track: stable
        run: frontend-server
    spec:
      volumes:
      - name: config
        configMap:
         name: nginx-config
         items:
         - key: config
           path: site.conf
      containers:
      - name: nginx
        image: nginx:1.7.9 
        ports:
        - containerPort: 80
          #hostPort: 8086  #to remove after debugging
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      


  
