apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: alpine-ampache
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: alpine-ampache
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50
