apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: php-apache
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: webserver
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50