apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: alpine-ampache
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: alpine-ampache
 minReplicas: 1
 maxReplicas: 2
 targetCPUUtilizationPercentage: 50