apiVersion: v1
kind: Service
metadata:
 name: mysql8-service
 labels:
  app: mysql8
spec:
 type: NodePort
 ports:
 - port: 3306
   protocol: TCP
 selector:
  app: mysql8
---
apiVersion: apps/v1 
kind: Deployment
metadata:
 name: mysql
spec:
 selector:
  matchLabels:
   app: mysql8
    #strategy:
      #type: Recreate
 template:
   metadata:
    labels:
     app: mysql8
   spec:
    containers:
    - name: mysql
      image: mysql:8.0  
      #imagePullPolicy: Never
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: .sweetpwd.
      - name: MYSQL_DATABASE
        value: my_db
      - name: MYSQL_USER
        value: db_user
      - name: MYSQL_PASSWORD
        value: .mypwd
      args: ["--default-authentication-plugin=mysql_native_password"]
      ports:
      - containerPort: 3306
        name: mysql8
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
       claimName: mysql-pvc



