apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: ampache-serv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: ampache-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ampache-serv
  template:
    metadata:
      labels:
        app: ampache-serv
    spec:
      containers:
      - name: php-alpine
        image: oneko/ampache-alpine-nginx
        #imagePullPolicy: Never
        ports:
        - containerPort: 80

