apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /code
      volumes:
      - name: hostvol
        persistentVolumeClaim:
         claimName: hostvol 
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: hostvol
          mountPath: /code
        command:
        - wget
        - "-O"
        - "/code/index.php"
        - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php

